#!/usr/bin/env python
from geometry_msgs.msg import Quaternion
import tf


def getEularfromQuaternion(orientation):
   #Orientation need to ba a data type where it has x,y,z,w component

    #Organise input data
    quaternion = [orientation.x, orientation.y, orientation.z, orientation.w]

    #Ultilise function eular_from_quaternion from tf.transformation
    euler = tf.transformations.euler_from_quaternion(quaternion)

    return euler



def main():
    data= Quaternion()
    data.x=0

    data.y=0

    data.z=-0.581519411491


    data.w=0.813532527966




    euler = getEularfromQuaternion(data)
    print("Roll=", euler[0])
    print("Pitch=", euler[1])
    print("Yaw=", euler[2])

if __name__ == '__main__':
    main()